### PR TITLE
now saves position and summoner preferences

### PR DESCRIPTION
**Pull request by xthesebx**
(position for every draft, summoners per queue)
also fixed a problem with tft setting the positions
regarding #43, saving runes will come in another pull requests in 1-2 days with implementation of runepages

### CODE REVIEW

**Comment by xthesebx** [comment]
Might have broken champ select chat, will look into it later

**Comment by xthesebx** [comment]
will look more into it later, either i remove the listener from ChampSelectChatUI or someone else figures out why the listener doesnt work anymore and everythig goes through ChatUI Listener

**Comment by Karakazz** [comment]
Chat, remember pos and summoners work fine from what I've tested just now.

**Comment by xthesebx** [comment]
fixes #57 too now

**Pull request merged**
