### PR TITLE
Reduce LOC for ledge json requests

### PR DESCRIPTION
**Pull request by FluentCoding**
This PR reduces LOC/code duplication by replacing the creation of each RequestBuilder with the headers `Authorization`, `User-Agent` and `Accept` with a method call to a newly created method [jsonRequest](https://github.com/FluentCoding/custom-league-client/blob/87f5b8277dfbef226cc7ca74d98c9c9201021e42/Core/src/main/java/com/hawolt/client/resources/ledge/AbstractLedgeEndpoint.java#L53-L67) in the base class AbstractLedgeEndpoint, available to each ledge class.

### CODE REVIEW

**Comment by slyk26** [comment]
pr's should go from hawolt:dev -> new branch -> merge into hawolt:dev again

@hawolt pls fix and protect the main branch in the settings

**Comment by hawolt** [comment]
please change to hawolt:dev as mentioned by @slyk26 - main branch should already be protected, will need to check back on this

**Comment by hawolt** [comment]
if you need assistance with changing the branch to the dev branch please let us know on discord, I will happily merge once changed

**Comment by FluentCoding** [comment]
> if you need assistance with changing the branch to the dev branch please let us know on discord, I will happily merge once changed

It's fine i'll do it tomorrow when i have time, should be easy to do anyways.

**Pull request merged**
